# Global Variables
###################################################################################
variable "aws_profile" {
    type        = string
    default     = "eks-beginner"
    description = "Profile name to access the AWS"
}

variable "aws_region" {
    type        = string
    default     = "eu-west-2"
    description = "AWS Region"
}

variable "aws_region_az" {
    type        = list
    default     = [ "eu-west-2a", "eu-west-2b", "eu-west-2c" ]
    description = "AWS Region Availability Zones"
}

variable "owner" {
    type        = string
    description = "Configuration Owner"
}

variable "environment" {
    type        = string
    default     = "dev"
    description = "Infrastructure environment"
}

# Security Group Variables
###################################################################################
variable "sg_ingress_proto" {
    type        = string
    default     = "tcp"
    description = "Protocol used for the ingress rule"
}

variable "sg_ingress_ssh" {
    type        = string
    default     = "22"
    description = "Port used for the ingress SSH rule"
}

variable "sg_ingress_nfs" {
    type        = string
    default     = "2049"
    description = "Port used for the ingress NFS rule"
}

variable "sg_egress_proto" {
    type        = string
    default     = "-1"
    description = "Protocol used for the egress rule"    
}

variable "sg_egress_all" {
    type        = string
    default     = "0"
    description = "Port used for the egress rule"
}

variable "sg_cidr_block" {
    type        = string
    default     = "0.0.0.0/0"
    description = "CIDR block for the ingress/egress rule"
}

# VPC(Virtual Private Cloud) Variables
###################################################################################
variable "vpc_cidr_block" {
    type        = string
    default     = "10.0.0.0/16"
    description = "CIDR block for the VPC"
}

variable "vpc_dns_support" {
    type        = bool
    default     = true
    description = "Enable DNS support in the VPC"
}

variable "vpc_dns_hostnames" {
    type        = bool
    default     = true
    description = "Enable DNS hostnames in the VPC"
}

# Subnet Variables
###################################################################################
variable "subnet_public_ip" {
    type        = bool
    default     = true
    description = "Assign Public IP to the instance launched into the subnet"
}

variable "subnet_public_cidrs" {
    type        = list
    default     = [ "10.0.10.0/24", "10.0.20.0/24", "10.0.30.0/24" ]
    description = "CIDR block for the public subnet"
}

# Route Table Variables
###################################################################################
variable "route_table_cidr_block" {
    type        = string
    default     = "0.0.0.0/0"
    description = "CIDR block for the Route Table"
}

# EFS Variables
###################################################################################
variable "efs_encrypted" {
    type        = bool
    default     = true
    description = "Encrypt file system"
}

variable "efs_performance_mode" {
    type        = string
    default     = "generalPurpose"
    description = "Maximum I/O"
}

variable "efs_creation_token" {
    type        = string
    default     = ""
    description = "A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform."
}

variable "efs_transition_to_ia" {
    type        = string
    default     = null
    description = "Indicates how long it takes to transition files to the IA storage class. Valid values: AFTER_7_DAYS, AFTER_14_DAYS, AFTER_30_DAYS, AFTER_60_DAYS, or AFTER_90_DAYS."
}

variable "efs_mount_path" {
    type        = string
    default     = "/mnt/efs"
    description = "EFS Mount directory path"
}

# Instance Variables
###################################################################################
variable "instance_ami_linux" {
    type        = string
    default     = "ami-02f5781cba46a5e8a"
    description = "Id of the AMI used"
}

variable "instance_type" {
    type        = string
    default     = "t2.micro"
    description = "Type of the Instance"
}

variable "key_pair" {
    type        = string
    default     = "london-KP"
    description = "SSH Key Pair used to connect"
}

variable "root_device_type" {
    type        = string
    default     = "gp2"
    description = "Type of the root block device"
}

variable "root_device_size" {
    type        = string
    default     = "30"
    description = "Size of the root block device"
}

variable "instances_linux" {
    type        = list
    default     = [ "a", "b", "c" ]
    description = "EC2 Instance list"
}